export const cardMock = [
  {
    title: "Pokémon GO",
    titleColor: "#fefe",
    description: "lorem ipsum",
    descriptionColor: "#4c1b90",
    background: "#b38aea",
    imagePath: "pokemon-go.jpg",
    imageAlt: "pokemon-go",
  },
  {
    title: "Nova série Pokémon",
    titleColor: "#fefe",
    background: "#ed6b2f",
    imagePath: "pokemon-new.webp",
    imageAlt: "pokemon-new-serie",
  },
  {
    title: "Pokémon",
    titleColor: "#fefe",
    background: "#e2350d",
    imagePath: "pokemons.jpg",
    imageAlt: "pokemons",
  },
  {
    title: "Aniversário",
    titleColor: "#fefe",
    description: "lorem ipsum",
    descriptionColor: "#4c1b90",
    background: "#31a7d7",
    imagePath: "pokemons-birth.jpg",
    imageAlt: "pokemons",
  },
  {
    title: "Pokémon",
    titleColor: "#fefe",
    description: "lorem ipsum",
    descriptionColor: "#31a7d7",
    background: "#1c53ba",
    imagePath: "pokemon-serie.webp",
    imageAlt: "pokemons",
  },
  {
    title: "Pikachu",
    titleColor: "#fefe",
    description: "lorem ipsum",
    descriptionColor: "#212121",
    background: "#e5bc2e",
    imagePath: "pikachu.jpg",
    imageAlt: "pokemons",
  },
];
